name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

jobs:

  test:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        arch: [ x86_64 ]
        python_version: [ "3.11" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install
        run: |
          pip install -r requirements.txt
          pip install . -v --no-build-isolation

#      - name: No JIT smoke test
#        run: |
#          pytest tests/torch_mlir/core.py

      - name: Unit tests
        run: |
          PYTHONPATH=tests pytest tests/unit

#      - name: Test vs. torch-mlir test-suite
#        run: |
#          pip install -r torch-mlir-full-requirements.txt
#          PYTHONPATH=tests/torch_mlir pytest tests/torch_mlir/main.py
